name: replika
description: Replika dart core for sending errors to the replika platform
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
